/**
 * @file render.js
 * @description DOM INJECTION MODULE — populates every static section of the page
 * by reading from the global data objects and building HTML strings.
 *
 * DEPENDS ON (must be loaded before this file):
 *   - site-data.js     → window.SITE_DATA
 *   - itinerary-data.js → window.ITINERARY_DATA
 *
 * EXPORTS (global functions, called by script.js):
 *   - renderSiteContent()  Orchestrator: calls all five section renderers below.
 *   - renderOverview()     Populates #overview-grid (cards) and #route-stops (visual).
 *   - renderTips()         Populates #tips-grid with tip cards.
 *   - renderPacking()      Populates #packing-grid with packing category cards.
 *   - renderBudget()       Populates #budget-tbody with JPY rows + .converted-val cells.
 *   - renderHotels()       Populates #quick-leg-pills and #itinerary-hotels-grid.
 *   - renderItinerary()    Populates #timeline with all 12 day-card accordions.
 *   - toggleDay(header)    Accordion open/close for a day card; also on window.toggleDay
 *                          so HTML onclick="toggleDay(this)" can reach it.
 *   - initDayCards()       Opens the first day card by default after render.
 *
 * BILINGUAL PATTERN:
 *   Every piece of text is wrapped in <span class="lang-en"> and <span class="lang-zh">.
 *   CSS on body.lang-en / body.lang-zh-hk controls visibility (defined in style.css).
 *
 * TO EDIT CONTENT: change site-data.js or itinerary-data.js — do NOT edit this file.
 * TO CHANGE LAYOUT: edit the template literals inside each render function below.
 */


/* ─── Orchestrator ─── */
function renderSiteContent() {
  renderOverview();
  renderTips();
  renderPacking();
  renderBudget();
  renderHotels();
}


/* ─── Overview Section ─── */
function renderOverview() {
  if (!window.SITE_DATA || !window.SITE_DATA.overview) return;
  const data = window.SITE_DATA.overview;

  const gridEl = document.getElementById('overview-grid');
  if (gridEl && data.cards) {
    gridEl.innerHTML = data.cards.map(card => `
      <div class="overview-card" id="${card.id}">
        <div class="ov-icon">${card.icon}</div>
        <h3>
          <span class="lang-en">${card.title.en}</span>
          <span class="lang-zh">${card.title.zh}</span>
        </h3>
        <p class="lang-en">${card.desc.en}</p>
        <p class="lang-zh">${card.desc.zh}</p>
      </div>
    `).join('');
  }

  const stopsEl = document.getElementById('route-stops');
  if (stopsEl && data.routeStops) {
    stopsEl.innerHTML = data.routeStops.map(stop => `
      <div class="route-stop jr-station-node" data-stop="${stop.label}">
        <!-- Above the line: Station Code + Kanji + Hiragana -->
        <div class="jr-station-top">
          <div class="jr-station-code" style="--code-color: ${stop.color};">
            <span class="jr-code-prefix">${stop.label}</span>
            <span class="jr-code-num">${stop.code}</span>
          </div>
          <div class="jr-station-kanji">${stop.kanji}</div>
          <div class="jr-station-kana">${stop.hiragana}</div>
        </div>

        <!-- Middle: Station Dot on the track -->
        <div class="jr-station-dot-wrapper">
          <div class="stop-dot ${stop.dotClass}" style="--dot-color: ${stop.color};">
            <span class="dot-inner-core"></span>
          </div>
        </div>

        <!-- Below the line: Romaji + Days Tag -->
        <div class="jr-station-bottom">
          <div class="jr-station-romaji">${stop.romaji}</div>
          <div class="jr-station-days">
            <span class="lang-en">${stop.days.en}</span>
            <span class="lang-zh">${stop.days.zh}</span>
          </div>
        </div>
      </div>
    `).join('');
  }
}


/* ─── Practical Tips Section ─── */
function renderTips() {
  if (!window.SITE_DATA || !window.SITE_DATA.tips) return;
  const tipsEl = document.getElementById('tips-grid');
  if (!tipsEl) return;

  tipsEl.innerHTML = window.SITE_DATA.tips.map(tip => {
    const itemsHtml = tip.items.map(item => `
      <li>
        <span class="lang-en">${item.en}</span>
        <span class="lang-zh">${item.zh}</span>
      </li>
    `).join('');

    return `
      <div class="tip-card" id="${tip.id}">
        <div class="tip-header">
          <span class="tip-icon">${tip.icon}</span>
          <h3>
            <span class="lang-en">${tip.title.en}</span>
            <span class="lang-zh">${tip.title.zh}</span>
          </h3>
        </div>
        <ul>
          ${itemsHtml}
        </ul>
      </div>
    `;
  }).join('');
}


/* ─── Packing Essentials Section ─── */
function renderPacking() {
  if (!window.SITE_DATA || !window.SITE_DATA.packing) return;
  const packEl = document.getElementById('packing-grid');
  if (!packEl) return;

  packEl.innerHTML = window.SITE_DATA.packing.map(pack => {
    const itemsHtml = pack.items.map(item => `
      <li>
        <span class="lang-en">${item.en}</span>
        <span class="lang-zh">${item.zh}</span>
      </li>
    `).join('');

    return `
      <div class="packing-card" id="${pack.id}">
        <h3>
          <span class="lang-en">${pack.icon} ${pack.title.en}</span>
          <span class="lang-zh">${pack.icon} ${pack.title.zh}</span>
        </h3>
        <ul>
          ${itemsHtml}
        </ul>
      </div>
    `;
  }).join('');
}


/* ─── Budget Table Section ─── */
function renderBudget() {
  if (!window.SITE_DATA || !window.SITE_DATA.budget) return;
  const tbodyEl = document.getElementById('budget-tbody');
  if (!tbodyEl) return;

  const data = window.SITE_DATA.budget;

  const rowsHtml = data.items.map(item => `
    <tr>
      <td>
        <span class="lang-en">${item.category.en}</span>
        <span class="lang-zh">${item.category.zh}</span>
      </td>
      <td>${item.jpy}</td>
      <td class="converted-val" data-min="${item.min}" data-max="${item.max}">
        ${item.initial}
      </td>
      <td>
        <span class="lang-en">${item.notes.en}</span>
        <span class="lang-zh">${item.notes.zh}</span>
      </td>
    </tr>
  `).join('');

  const totalHtml = `
    <tr class="budget-total">
      <td>
        <span class="lang-en">${data.total.category.en}</span>
        <span class="lang-zh">${data.total.category.zh}</span>
      </td>
      <td>${data.total.jpy}</td>
      <td class="converted-val budget-total-val" data-min="${data.total.min}" data-max="${data.total.max}">
        ${data.total.initial}
      </td>
      <td>
        <span class="lang-en">${data.total.notes.en}</span>
        <span class="lang-zh">${data.total.notes.zh}</span>
      </td>
    </tr>
  `;

  tbodyEl.innerHTML = rowsHtml + totalHtml;
}


/* ─── Hotels & Ryokan Section ─── */
function renderHotels() {
  if (!window.SITE_DATA || !window.SITE_DATA.hotels) return;
  const data = window.SITE_DATA.hotels;

  // Quick leg pills
  const quickLegsEl = document.getElementById('quick-leg-pills');
  if (quickLegsEl && data.quickLegs) {
    quickLegsEl.innerHTML = data.quickLegs.map(leg => `
      <button class="leg-pill ${leg.active ? 'active' : ''}" data-dest="${leg.dest}" data-checkin="${leg.checkin}" data-checkout="${leg.checkout}">
        <span class="lang-en">${leg.label.en}</span>
        <span class="lang-zh">${leg.label.zh}</span>
      </button>
    `).join('');
  }

  // Curated hotel leg cards
  const gridEl = document.getElementById('itinerary-hotels-grid');
  if (gridEl && data.legs) {
    gridEl.innerHTML = data.legs.map(leg => {
      const tagsHtml = leg.tags.map(tag => `<span>${tag}</span>`).join('');
      const badgeCls = leg.badgeClass ? ` ${leg.badgeClass}` : '';
      const cardCls = leg.highlight ? 'hotel-leg-card highlight-card' : 'hotel-leg-card';
      const bookingUrl = `https://www.booking.com/searchresults.html?ss=${encodeURIComponent(leg.dest)}&checkin=${leg.checkin}&checkout=${leg.checkout}&group_adults=3&no_rooms=1`;

      return `
        <div class="${cardCls}">
          <div class="hotel-leg-badge${badgeCls}">
            <span class="lang-en">${leg.nights.en}</span>
            <span class="lang-zh">${leg.nights.zh}</span>
          </div>
          <div class="hotel-leg-body">
            <h4>
              <span class="lang-en">${leg.title.en}</span>
              <span class="lang-zh">${leg.title.zh}</span>
            </h4>
            <p class="hotel-leg-dates">${leg.dates}</p>
            <p class="hotel-leg-desc">
              <span class="lang-en">${leg.desc.en}</span>
              <span class="lang-zh">${leg.desc.zh}</span>
            </p>
            <div class="hotel-leg-tags">
              ${tagsHtml}
            </div>
            <a href="${bookingUrl}" target="_blank" rel="noopener" class="hotel-leg-btn" data-dest="${leg.dest}" data-checkin="${leg.checkin}" data-checkout="${leg.checkout}">
              <span class="lang-en">${leg.btnText.en}</span>
              <span class="lang-zh">${leg.btnText.zh}</span>
            </a>
          </div>
        </div>
      `;
    }).join('');
  }
}


/* ─── Itinerary Timeline ─── */
function renderItinerary() {
  const container = document.getElementById('timeline');
  if (!container || !window.ITINERARY_DATA) return;

  const html = window.ITINERARY_DATA.map(day => {
    // Build tag chips
    const tagsHtml = day.tags.map(tag => {
      if (tag.type === 'city') {
        return `<span class="tag tag-city">${tag.text}</span>`;
      } else if (tag.type === 'transport') {
        return `<span class="tag tag-transport">${tag.text}</span>`;
      } else if (tag.type === 'pace') {
        return `
          <span class="tag tag-pace">
            <span class="lang-en">${tag.en}</span>
            <span class="lang-zh">${tag.zh}</span>
          </span>`;
      } else if (tag.type === 'special') {
        if (tag.text) {
          return `<span class="tag tag-special">${tag.text}</span>`;
        } else {
          return `
            <span class="tag tag-special">
              <span class="lang-en">${tag.en}</span>
              <span class="lang-zh">${tag.zh}</span>
            </span>`;
        }
      }
      return '';
    }).join('');

    // Build time blocks
    const blocksHtml = day.blocks.map(block => {
      const mealHtml = block.activity.meal ? `
        <div class="meal-rec">
          <span class="meal-icon">${block.activity.meal.icon}</span>
          <span class="lang-en">${block.activity.meal.en}</span>
          <span class="lang-zh">${block.activity.meal.zh}</span>
        </div>` : '';

      return `
        <div class="timeline-block">
          <div class="time-badge">
            <span class="lang-en">${block.time.en}</span>
            <span class="lang-zh">${block.time.zh}</span>
          </div>
          <div class="activity">
            <h4>
              <span class="lang-en">${block.activity.title.en}</span>
              <span class="lang-zh">${block.activity.title.zh}</span>
            </h4>
            <p class="lang-en">${block.activity.desc.en}</p>
            <p class="lang-zh">${block.activity.desc.zh}</p>
            ${mealHtml}
          </div>
        </div>`;
    }).join('');

    // Optional daily tip
    const tipHtml = day.tip ? `
      <div class="day-tip">
        <span class="lang-en">${day.tip.en}</span>
        <span class="lang-zh">${day.tip.zh}</span>
      </div>` : '';

    return `
      <!-- ════ DAY ${day.dayNum} ════ -->
      <div class="day-card" data-region="${day.region}" id="${day.id}">
        <div class="day-header" onclick="toggleDay(this)">
          <div class="day-badge">
            <span class="day-num">${day.dayNum}</span>
            <span class="day-date">${day.date}</span>
          </div>
          <div class="day-info">
            <h3>
              <span class="lang-en">${day.title.en}</span>
              <span class="lang-zh">${day.title.zh}</span>
            </h3>
            <div class="day-tags">
              ${tagsHtml}
            </div>
          </div>
          <div class="day-chevron">▼</div>
        </div>
        <div class="day-body">
          ${blocksHtml}
          ${tipHtml}
        </div>
      </div>`;
  }).join('\n');

  container.innerHTML = html;
}


/* ─── Day Card Accordion ─── */
function toggleDay(header) {
  const card = header.closest('.day-card');
  const wasOpen = card.classList.contains('open');

  // Close all other open cards
  document.querySelectorAll('.day-card.open').forEach(c => {
    if (c !== card) c.classList.remove('open');
  });

  // Toggle current card
  card.classList.toggle('open', !wasOpen);

  // Smooth scroll into view when opening
  if (!wasOpen) {
    setTimeout(() => {
      card.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 150);
  }
}

// Expose toggleDay to inline onclick handlers
window.toggleDay = toggleDay;


/* ─── Day Cards Init ─── */
function initDayCards() {
  // Open the first day card by default
  const firstCard = document.querySelector('.day-card');
  if (firstCard) firstCard.classList.add('open');
}
