/**
 * @file render.js
 * @description DOM INJECTION MODULE — populates every static section of the page
 * by reading from the global data objects and building HTML strings.
 *
 * DEPENDS ON (must be loaded before this file):
 *   - site-data.js      → window.SITE_DATA
 *   - itinerary-data.js → window.ITINERARY_DATA
 *
 * EXPORTS (global functions, called by script.js):
 *   - renderSiteContent()  Orchestrator: calls all five section renderers below.
 *   - renderOverview()     Populates #overview-grid (3 summary cards) and #route-stops
 *                          (JR Station Sign route board with 7 bilingual station nodes).
 *   - renderTips()         Populates #tips-grid with tip cards.
 *   - renderPacking()      Populates #packing-grid with packing category cards.
 *   - renderBudget()       Populates #budget-tbody with JPY rows + .converted-val cells.
 *   - renderHotels()       Populates #quick-leg-pills and #itinerary-hotels-grid.
 *   - renderItinerary()    Populates #timeline with all 12 day-card accordions.
 *   - toggleDay(header)    Accordion open/close for a day card; also on window.toggleDay
 *                          so HTML onclick="toggleDay(this)" can reach it.
 *   - initDayCards()       Opens the first day card by default after render.
 *
 * BILINGUAL PATTERN:
 *   Every piece of text is wrapped in <span class="lang-en"> and <span class="lang-zh">.
 *   CSS on body.lang-en / body.lang-zh-hk controls visibility (defined in style.css).
 *
 * JR STATION SIGN ROUTE BOARD (renderOverview → #route-stops):
 *   Each .jr-station-node uses a 3-row CSS Grid (grid-template-rows: 78px 24px 54px):
 *     Row 1 (.jr-station-top):    Station code badge + Kanji name + Hiragana reading
 *     Row 2 (.jr-station-dot-wrapper): Station dot centred on the horizontal track line
 *     Row 3 (.jr-station-bottom): Romaji name + bilingual day badge
 *   The horizontal .route-line is absolutely positioned at top: 90px (= 78px + 24px/2)
 *   to land at the vertical centre of Row 2 across ALL stations simultaneously.
 *
 * TO EDIT CONTENT: change site-data.js or itinerary-data.js — do NOT edit this file.
 * TO CHANGE LAYOUT: edit the template literals inside each render function below.
 */


/* ─── Orchestrator ─── */
function renderSiteContent() {
  renderOverview();
  renderCarReturn();
  renderCarRental();
  renderTips();
  renderPacking();
  renderBudget();
  renderHotels();
}


/* ─── Car Rental Search Section ───────────────────────────────
 *  Reads SITE_DATA.carRental and populates:
 *    #rental-search-card    — intro callout + pickup location pills
 *    #rental-companies-grid — 3 company cards (Toyota / Nissan / Nippon)
 *
 *  Pickup pills pre-fill a hidden input; clicking a company's
 *  "Book Now" button opens the company's English search page in a
 *  new tab. The pickup value is appended as a query param where
 *  supported, or just shown as a context label.
 * ──────────────────────────────────────────────────────────── */
function renderCarRental() {
  if (!window.SITE_DATA || !window.SITE_DATA.carRental) return;
  const data = window.SITE_DATA.carRental;

  // ── Search card: intro + pickup pills ──
  const searchEl = document.getElementById('rental-search-card');
  if (searchEl) {
    const pillsHtml = data.quickPickup.map((p, i) => `
      <button class="rental-pickup-pill${i === 0 ? ' active' : ''}"
              onclick="selectRentalPickup(this)"
              data-location="${p.location}">
        <span class="lang-en">${p.label.en}</span>
        <span class="lang-zh">${p.label.zh}</span>
      </button>`).join('');

    searchEl.innerHTML = `
      <div class="rental-search-header">
        <div class="rental-search-brand">
          <span class="rental-brand-icon">🚗</span>
          <div>
            <h3>
              <span class="lang-en">Japan Rental Car Finder</span>
              <span class="lang-zh">日本租車搜尋器</span>
            </h3>
            <p class="rental-intro">
              <span class="lang-en">${data.intro.en}</span>
              <span class="lang-zh">${data.intro.zh}</span>
            </p>
          </div>
        </div>
        <div class="rental-pickup-row">
          <span class="rental-pickup-label">
            <span class="lang-en">📍 Pickup location:</span>
            <span class="lang-zh">📍 取車地點：</span>
          </span>
          <div class="rental-pickup-pills">${pillsHtml}</div>
        </div>
      </div>
    `;
  }

  // ── Vehicle size recommendation ──
  const vehicleEl = document.getElementById('rental-vehicle-rec');
  if (vehicleEl && data.vehicleRec) {
    const vr = data.vehicleRec;
    const picksHtml = vr.picks.map(p => `
      <div class="vr-card vr-${p.verdict}" id="${p.id}">
        <div class="vr-card-top">
          <span class="vr-icon">${p.icon}</span>
          <div class="vr-info">
            <h4 class="vr-category">
              <span class="lang-en">${p.category.en}</span>
              <span class="lang-zh">${p.category.zh}</span>
            </h4>
            <p class="vr-models">
              <span class="lang-en">${p.models.en}</span>
              <span class="lang-zh">${p.models.zh}</span>
            </p>
          </div>
          <span class="vr-badge ${p.badgeClass}">
            <span class="lang-en">${p.badge.en}</span>
            <span class="lang-zh">${p.badge.zh}</span>
          </span>
        </div>
        <p class="vr-boot">
          🧳 <span class="lang-en"><strong>Boot:</strong> ${p.boot.en}</span>
              <span class="lang-zh"><strong>尾箱：</strong>${p.boot.zh}</span>
        </p>
        <p class="vr-why">
          <span class="lang-en">${p.why.en}</span>
          <span class="lang-zh">${p.why.zh}</span>
        </p>
      </div>`).join('');

    vehicleEl.innerHTML = `
      <div class="vr-heading">
        <span class="vr-heading-icon">🧳</span>
        <div>
          <h3 class="vr-heading-title">
            <span class="lang-en">Which Car Size for Your Group?</span>
            <span class="lang-zh">應選哪種車型？</span>
          </h3>
          <p class="vr-luggage-context">
            <span class="lang-en">${vr.luggageContext.en}</span>
            <span class="lang-zh">${vr.luggageContext.zh}</span>
          </p>
        </div>
      </div>
      <div class="vr-grid">${picksHtml}</div>
    `;
  }

  // ── Company cards ──
  const gridEl = document.getElementById('rental-companies-grid');
  if (gridEl) {
    gridEl.innerHTML = data.companies.map(co => {
      const featuresHtml = co.features.map(f => `
        <li>
          <span class="lang-en">${f.en}</span>
          <span class="lang-zh">${f.zh}</span>
        </li>`).join('');

      return `
        <div class="rental-card" id="${co.id}">
          <div class="rental-card-header">
            <span class="rental-logo">${co.logo}</span>
            <div class="rental-name-wrap">
              <h3 class="rental-name">${co.name}</h3>
              <p class="rental-name-jp">${co.nameJp}</p>
            </div>
            <span class="rental-badge ${co.badgeClass}">
              <span class="lang-en">${co.badge.en}</span>
              <span class="lang-zh">${co.badge.zh}</span>
            </span>
          </div>
          <p class="rental-tagline">
            <span class="lang-en">${co.tagline.en}</span>
            <span class="lang-zh">${co.tagline.zh}</span>
          </p>
          <ul class="rental-features">${featuresHtml}</ul>
          <div class="rental-note">
            <span class="lang-en">${co.note.en}</span>
            <span class="lang-zh">${co.note.zh}</span>
          </div>
          <a href="${co.searchUrl}" target="_blank" rel="noopener"
             class="rental-book-btn" id="${co.id}-btn">
            <span class="lang-en">Book on ${co.name} ↗</span>
            <span class="lang-zh">前往 ${co.nameJp} 預訂 ↗</span>
          </a>
        </div>
      `;
    }).join('');
  }
}

/* Allow pickup pills to highlight active state (no page reload needed) */
function selectRentalPickup(btn) {
  const all = btn.closest('.rental-pickup-pills').querySelectorAll('.rental-pickup-pill');
  all.forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
}
window.selectRentalPickup = selectRentalPickup;


/* ─── Car Return Decision Helper Section ───
 *  Reads SITE_DATA.carReturn and populates:
 *    #car-return-context  — introductory paragraph
 *    #car-return-grid     — three option cards (Nagoya / Kyoto / Osaka)
 *    #car-return-rec      — bottom recommendation callout
 *
 *  Each card uses verdict CSS classes:
 *    .verdict-current        — green "Current Plan" badge
 *    .verdict-caution        — amber "Possible — But Tricky" badge
 *    .verdict-notrecommended — red  "Not Recommended" badge
 * ────────────────────────────────────────── */
function renderCarReturn() {
  if (!window.SITE_DATA || !window.SITE_DATA.carReturn) return;
  const data = window.SITE_DATA.carReturn;
  const lang = document.body.classList.contains('lang-zh-hk') ? 'zh' : 'en';

  // Context paragraph
  const ctxEl = document.getElementById('car-return-context');
  if (ctxEl) {
    ctxEl.innerHTML = `
      <span class="lang-en">${data.context.en}</span>
      <span class="lang-zh">${data.context.zh}</span>
    `;
  }

  // Option cards
  const gridEl = document.getElementById('car-return-grid');
  if (gridEl) {
    gridEl.innerHTML = data.options.map(opt => {
      const prosHtml = opt.pros.map(p => `
        <li class="cr-pro">
          <span class="cr-bullet cr-bullet-pro">✓</span>
          <span class="lang-en">${p.en}</span>
          <span class="lang-zh">${p.zh}</span>
        </li>`).join('');

      const consHtml = opt.cons.map(c => `
        <li class="cr-con">
          <span class="cr-bullet cr-bullet-con">✗</span>
          <span class="lang-en">${c.en}</span>
          <span class="lang-zh">${c.zh}</span>
        </li>`).join('');

      // Tips panel ("If you choose this" recommendations)
      const tipsHtml = (opt.tips || []).map(tip => `
        <div class="cr-tip-item">
          <span class="cr-tip-icon">${tip.icon}</span>
          <div class="cr-tip-body">
            <strong class="cr-tip-label">
              <span class="lang-en">${tip.label.en}</span>
              <span class="lang-zh">${tip.label.zh}</span>
            </strong>
            <p class="cr-tip-detail">
              <span class="lang-en">${tip.detail.en}</span>
              <span class="lang-zh">${tip.detail.zh}</span>
            </p>
          </div>
        </div>
      `).join('');

      return `
        <div class="cr-card verdict-${opt.verdict}" id="${opt.id}">
          <div class="cr-card-header">
            <div class="cr-city-icon">${opt.icon}</div>
            <div class="cr-city-info">
              <h3 class="cr-city-name">
                <span class="lang-en">${opt.title.en}</span>
                <span class="lang-zh">${opt.title.zh}</span>
              </h3>
              <p class="cr-subtitle">
                <span class="lang-en">${opt.subtitle.en}</span>
                <span class="lang-zh">${opt.subtitle.zh}</span>
              </p>
            </div>
            <div class="cr-verdict-badge verdict-badge-${opt.verdict}">
              <span class="lang-en">${opt.verdictLabel.en}</span>
              <span class="lang-zh">${opt.verdictLabel.zh}</span>
            </div>
          </div>
          <div class="cr-lists">
            <div class="cr-list-col">
              <h4 class="cr-list-heading cr-pros-heading">
                <span class="lang-en">✅ Pros</span>
                <span class="lang-zh">✅ 優點</span>
              </h4>
              <ul class="cr-list">${prosHtml}</ul>
            </div>
            <div class="cr-list-col">
              <h4 class="cr-list-heading cr-cons-heading">
                <span class="lang-en">❌ Cons</span>
                <span class="lang-zh">❌ 缺點</span>
              </h4>
              <ul class="cr-list">${consHtml}</ul>
            </div>
          </div>
          ${tipsHtml ? `
          <div class="cr-tips-toggle" onclick="toggleCarTips(this)" role="button" aria-expanded="false">
            <span class="cr-tips-toggle-icon">🗺️</span>
            <span class="cr-tips-toggle-label">
              <span class="lang-en">If you choose this — Hotels, Food &amp; Logistics</span>
              <span class="lang-zh">若選擇此方案 — 住宿、美食及行李安排</span>
            </span>
            <span class="cr-chevron">▼</span>
          </div>
          <div class="cr-tips-panel">
            ${tipsHtml}
          </div>` : ''}
        </div>
      `;
    }).join('');
  }

  // Bottom recommendation callout
  const recEl = document.getElementById('car-return-rec');
  if (recEl) {
    recEl.innerHTML = `
      <span class="lang-en">${data.recommendation.en}</span>
      <span class="lang-zh">${data.recommendation.zh}</span>
    `;
  }
}


/* ─── Car Tips Accordion Toggle ───
 * Called by onclick="toggleCarTips(this)" on .cr-tips-toggle elements.
 * Toggles .open on the sibling .cr-tips-panel and rotates the chevron.
 * ─────────────────────────────── */
function toggleCarTips(btn) {
  const panel = btn.nextElementSibling; // .cr-tips-panel
  const chevron = btn.querySelector('.cr-chevron');
  const isOpen = panel.classList.toggle('open');
  btn.setAttribute('aria-expanded', isOpen);
  if (chevron) chevron.style.transform = isOpen ? 'rotate(180deg)' : '';
}
window.toggleCarTips = toggleCarTips; // expose for inline onclick


/* ─── Overview Section ─── */
function renderOverview() {
  if (!window.SITE_DATA || !window.SITE_DATA.overview) return;
  const data = window.SITE_DATA.overview;

  const gridEl = document.getElementById('overview-grid');
  if (gridEl && data.cards) {
    gridEl.innerHTML = data.cards.map(card => `
      <div class="overview-card" id="${card.id}">
        <div class="ov-icon">${card.icon}</div>
        <h3>
          <span class="lang-en">${card.title.en}</span>
          <span class="lang-zh">${card.title.zh}</span>
        </h3>
        <p class="lang-en">${card.desc.en}</p>
        <p class="lang-zh">${card.desc.zh}</p>
      </div>
    `).join('');
  }

  const stopsEl = document.getElementById('route-stops');
  if (stopsEl && data.routeStops) {
    stopsEl.innerHTML = data.routeStops.map(stop => `
      <div class="route-stop jr-station-node" data-stop="${stop.label}">
        <!-- Above the line: Station Code + Kanji + Hiragana -->
        <div class="jr-station-top">
          <div class="jr-station-code" style="--code-color: ${stop.color};">
            <span class="jr-code-prefix">${stop.label}</span>
            <span class="jr-code-num">${stop.code}</span>
          </div>
          <div class="jr-station-kanji">${stop.kanji}</div>
          <div class="jr-station-kana">${stop.hiragana}</div>
        </div>

        <!-- Middle: Station Dot on the track -->
        <div class="jr-station-dot-wrapper">
          <div class="stop-dot ${stop.dotClass}" style="--dot-color: ${stop.color};">
            <span class="dot-inner-core"></span>
          </div>
        </div>

        <!-- Below the line: Romaji + Days Tag -->
        <div class="jr-station-bottom">
          <div class="jr-station-romaji">${stop.romaji}</div>
          <div class="jr-station-days">
            <span class="lang-en">${stop.days.en}</span>
            <span class="lang-zh">${stop.days.zh}</span>
          </div>
        </div>
      </div>
    `).join('');
  }
}


/* ─── Practical Tips Section ─── */
function renderTips() {
  if (!window.SITE_DATA || !window.SITE_DATA.tips) return;
  const tipsEl = document.getElementById('tips-grid');
  if (!tipsEl) return;

  tipsEl.innerHTML = window.SITE_DATA.tips.map(tip => {
    const itemsHtml = tip.items.map(item => `
      <li>
        <span class="lang-en">${item.en}</span>
        <span class="lang-zh">${item.zh}</span>
      </li>
    `).join('');

    return `
      <div class="tip-card" id="${tip.id}">
        <div class="tip-header">
          <span class="tip-icon">${tip.icon}</span>
          <h3>
            <span class="lang-en">${tip.title.en}</span>
            <span class="lang-zh">${tip.title.zh}</span>
          </h3>
        </div>
        <ul>
          ${itemsHtml}
        </ul>
      </div>
    `;
  }).join('');
}


/* ─── Packing Essentials Section ─── */
function renderPacking() {
  if (!window.SITE_DATA || !window.SITE_DATA.packing) return;
  const packEl = document.getElementById('packing-grid');
  if (!packEl) return;

  packEl.innerHTML = window.SITE_DATA.packing.map(pack => {
    const itemsHtml = pack.items.map(item => `
      <li>
        <span class="lang-en">${item.en}</span>
        <span class="lang-zh">${item.zh}</span>
      </li>
    `).join('');

    return `
      <div class="packing-card" id="${pack.id}">
        <h3>
          <span class="lang-en">${pack.icon} ${pack.title.en}</span>
          <span class="lang-zh">${pack.icon} ${pack.title.zh}</span>
        </h3>
        <ul>
          ${itemsHtml}
        </ul>
      </div>
    `;
  }).join('');
}


/* ─── Budget Table Section ─── */
function renderBudget() {
  if (!window.SITE_DATA || !window.SITE_DATA.budget) return;
  const tbodyEl = document.getElementById('budget-tbody');
  if (!tbodyEl) return;

  const data = window.SITE_DATA.budget;

  const rowsHtml = data.items.map(item => `
    <tr>
      <td>
        <span class="lang-en">${item.category.en}</span>
        <span class="lang-zh">${item.category.zh}</span>
      </td>
      <td>${item.jpy}</td>
      <td class="converted-val" data-min="${item.min}" data-max="${item.max}">
        ${item.initial}
      </td>
      <td>
        <span class="lang-en">${item.notes.en}</span>
        <span class="lang-zh">${item.notes.zh}</span>
      </td>
    </tr>
  `).join('');

  const totalHtml = `
    <tr class="budget-total">
      <td>
        <span class="lang-en">${data.total.category.en}</span>
        <span class="lang-zh">${data.total.category.zh}</span>
      </td>
      <td>${data.total.jpy}</td>
      <td class="converted-val budget-total-val" data-min="${data.total.min}" data-max="${data.total.max}">
        ${data.total.initial}
      </td>
      <td>
        <span class="lang-en">${data.total.notes.en}</span>
        <span class="lang-zh">${data.total.notes.zh}</span>
      </td>
    </tr>
  `;

  tbodyEl.innerHTML = rowsHtml + totalHtml;
}


/* ─── Hotels & Ryokan Section ─── */
function renderHotels() {
  if (!window.SITE_DATA || !window.SITE_DATA.hotels) return;
  const data = window.SITE_DATA.hotels;

  // Quick leg pills
  const quickLegsEl = document.getElementById('quick-leg-pills');
  if (quickLegsEl && data.quickLegs) {
    quickLegsEl.innerHTML = data.quickLegs.map(leg => `
      <button class="leg-pill ${leg.active ? 'active' : ''}" data-dest="${leg.dest}" data-checkin="${leg.checkin}" data-checkout="${leg.checkout}">
        <span class="lang-en">${leg.label.en}</span>
        <span class="lang-zh">${leg.label.zh}</span>
      </button>
    `).join('');
  }

  // Curated hotel leg cards
  const gridEl = document.getElementById('itinerary-hotels-grid');
  if (gridEl && data.legs) {
    gridEl.innerHTML = data.legs.map(leg => {
      const tagsHtml = leg.tags.map(tag => `<span>${tag}</span>`).join('');
      const badgeCls = leg.badgeClass ? ` ${leg.badgeClass}` : '';
      const cardCls = leg.highlight ? 'hotel-leg-card highlight-card' : 'hotel-leg-card';
      const bookingUrl = `https://www.booking.com/searchresults.html?ss=${encodeURIComponent(leg.dest)}&checkin=${leg.checkin}&checkout=${leg.checkout}&group_adults=3&no_rooms=1`;

      return `
        <div class="${cardCls}">
          <div class="hotel-leg-badge${badgeCls}">
            <span class="lang-en">${leg.nights.en}</span>
            <span class="lang-zh">${leg.nights.zh}</span>
          </div>
          <div class="hotel-leg-body">
            <h4>
              <span class="lang-en">${leg.title.en}</span>
              <span class="lang-zh">${leg.title.zh}</span>
            </h4>
            <p class="hotel-leg-dates">${leg.dates}</p>
            <p class="hotel-leg-desc">
              <span class="lang-en">${leg.desc.en}</span>
              <span class="lang-zh">${leg.desc.zh}</span>
            </p>
            <div class="hotel-leg-tags">
              ${tagsHtml}
            </div>
            <a href="${bookingUrl}" target="_blank" rel="noopener" class="hotel-leg-btn" data-dest="${leg.dest}" data-checkin="${leg.checkin}" data-checkout="${leg.checkout}">
              <span class="lang-en">${leg.btnText.en}</span>
              <span class="lang-zh">${leg.btnText.zh}</span>
            </a>
          </div>
        </div>
      `;
    }).join('');
  }
}


/* ─── Itinerary Timeline ─── */
function renderItinerary() {
  const container = document.getElementById('timeline');
  if (!container || !window.ITINERARY_DATA) return;

  const html = window.ITINERARY_DATA.map(day => {
    // Build tag chips
    const tagsHtml = day.tags.map(tag => {
      if (tag.type === 'city') {
        return `<span class="tag tag-city">${tag.text}</span>`;
      } else if (tag.type === 'transport') {
        return `<span class="tag tag-transport">${tag.text}</span>`;
      } else if (tag.type === 'pace') {
        return `
          <span class="tag tag-pace">
            <span class="lang-en">${tag.en}</span>
            <span class="lang-zh">${tag.zh}</span>
          </span>`;
      } else if (tag.type === 'special') {
        if (tag.text) {
          return `<span class="tag tag-special">${tag.text}</span>`;
        } else {
          return `
            <span class="tag tag-special">
              <span class="lang-en">${tag.en}</span>
              <span class="lang-zh">${tag.zh}</span>
            </span>`;
        }
      }
      return '';
    }).join('');

    // Build time blocks
    const blocksHtml = day.blocks.map(block => {
      const mealHtml = block.activity.meal ? `
        <div class="meal-rec">
          <span class="meal-icon">${block.activity.meal.icon}</span>
          <span class="lang-en">${block.activity.meal.en}</span>
          <span class="lang-zh">${block.activity.meal.zh}</span>
        </div>` : '';

      return `
        <div class="timeline-block">
          <div class="time-badge">
            <span class="lang-en">${block.time.en}</span>
            <span class="lang-zh">${block.time.zh}</span>
          </div>
          <div class="activity">
            <h4>
              <span class="lang-en">${block.activity.title.en}</span>
              <span class="lang-zh">${block.activity.title.zh}</span>
            </h4>
            <p class="lang-en">${block.activity.desc.en}</p>
            <p class="lang-zh">${block.activity.desc.zh}</p>
            ${mealHtml}
          </div>
        </div>`;
    }).join('');

    // Optional daily tip
    const tipHtml = day.tip ? `
      <div class="day-tip">
        <span class="lang-en">${day.tip.en}</span>
        <span class="lang-zh">${day.tip.zh}</span>
      </div>` : '';

    return `
      <!-- ════ DAY ${day.dayNum} ════ -->
      <div class="day-card" data-region="${day.region}" id="${day.id}">
        <div class="day-header" onclick="toggleDay(this)">
          <div class="day-badge">
            <span class="day-num">${day.dayNum}</span>
            <span class="day-date">${day.date}</span>
          </div>
          <div class="day-info">
            <h3>
              <span class="lang-en">${day.title.en}</span>
              <span class="lang-zh">${day.title.zh}</span>
            </h3>
            <div class="day-tags">
              ${tagsHtml}
            </div>
          </div>
          <div class="day-chevron">▼</div>
        </div>
        <div class="day-body">
          <div class="day-body-content">
            ${blocksHtml}
            ${tipHtml}
          </div>
          <div class="day-map" id="day-map-${day.id}"></div>
        </div>
      </div>`;
  }).join('\n');

  container.innerHTML = html;
}


/* ─── Day Card Accordion ─── */
function toggleDay(header) {
  const card = header.closest('.day-card');
  const wasOpen = card.classList.contains('open');

  // Close all other open cards
  document.querySelectorAll('.day-card.open').forEach(c => {
    if (c !== card) c.classList.remove('open');
  });

  // Toggle current card
  card.classList.toggle('open', !wasOpen);

  // Lazy-init the mini map when opening
  if (!wasOpen && typeof window.initDayMap === 'function') {
    const dayId = card.id;
    // Small delay so the card is visible before Leaflet measures the container
    setTimeout(() => window.initDayMap(dayId), 80);
  }

  // Smooth scroll into view when opening
  if (!wasOpen) {
    setTimeout(() => {
      card.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 150);
  }
}

// Expose toggleDay to inline onclick handlers
window.toggleDay = toggleDay;


/* ─── Day Cards Init ─── */
function initDayCards() {
  // Open the first day card by default
  const firstCard = document.querySelector('.day-card');
  if (firstCard) firstCard.classList.add('open');
}
